### ISSUE TITLE
Heiman SMOK_YDLV10 smoke detector

### ISSUE THREAD

**Issue by SEWADE** [ioBroker/ioBroker.zigbee#137]
Hi,

it is possible to add support for Heiman SMOK_YDLV10 smoke detector?

Please see at zigbee2mqtt: 
https://github.com/Koenkk/zigbee2mqtt/issues/384
https://github.com/Koenkk/zigbee2mqtt/issues/279

If you need some logs or something else, I have a couple of smoke detectors. Let me know.

BR
Sebastian

**Comment by arteck** [comment]
https://github.com/arteck/ioBroker.zigbee/blob/fb3137ad1f17e0a7a64584f5f94a26c6ec2566d0/lib/devstates.js#L1656

done but not merged

**Comment by SEWADE** [comment]
Hi arteck,

thanks a lot.
With your repo the smoke detectors are supported. 
Values of "Link quality" and "Smoke leak" (after press the test button) are detected and available, "Battery percent" still not.

One question. Is there any possibility to activate the siren, so that i can create groups of smoke detectors with ioBroker? That would be a big benefit.

BR
Sebastian

**Comment by Thomas1305** [comment]
Hi arteck,
i have the lastet version 0.9.2 and i was able to pair the smoke detektor.
But i dont get a state on the indicator.alarm.fire
Even not, if i press the test button. See picture below
![unbenannt](https://user-images.githubusercontent.com/46224531/53547480-74c3c700-3b2f-11e9-8398-cf71fce327e9.PNG)

**Comment by arteck** [comment]
i know .. this is on all smoke's.. test it plz with smoke .. not with the button.

battery is a issue ... i know

**Comment by Thomas1305** [comment]
ok, i´ll test it when i´m at home.
What do you mean with battery issue?

and my xiaomi honeywell smoke detector shows a state (see picture)
![unbenannt](https://user-images.githubusercontent.com/46224531/53565696-6c34b600-3b5a-11e9-949b-bcaa2b9dc814.PNG)

**Comment by arteck** [comment]
the i cant see the battery stats on my SMOK_YDLV10..

**Comment by Thomas1305** [comment]
@arteck 
i´ve tested it today.
the smoke detector starts the siren, but i don´t get a state for "smoke leak detected".
Maybe there is a little difference between the Heiman and the Schwaiger smoke detector.
But it dont believe that.

**Comment by Thomas1305** [comment]
so what can i do?

**Comment by Thomas1305** [comment]
does anyone have an idea how to fix it?

**Comment by Romka83** [comment]
I have the same Problem -> i don´t get a state for "smoke leak detected". 
Is there a fix for this Problem?

**Comment by Thomas1305** [comment]
any news.
i still get no state for "smoke leak detected"
