### ISSUE TITLE
kein Datenpunkt "action" bei Aqara D1 

### ISSUE THREAD

**Issue by nicomania** [ioBroker/ioBroker.zigbee#1426]
Bei den Aqara D1 fehlt der Datenpunkt `action`, welcher bei `legacy: false` eigentlich vorhanden sein sollte. Der Datenpunkt `click` wird nicht aktualisiert und steht immer auf null. Eines von beiden sollte jedoch funktionieren, je nach Einstellung von `legacy`, wie es hier auch beschrieben steht: [https://www.zigbee2mqtt.io/devices/WXKG06LM.html](https://www.zigbee2mqtt.io/devices/WXKG06LM.html). 

Alle anderen Taster (z.B. doppel und dreifach) von Aquara D1 funktionieren prima. Der Einzeltaster jedoch ist damit momentan unbenutzbar.

![image](https://user-images.githubusercontent.com/35151132/165119492-d8de2b7a-bf53-475e-8f59-f62d33488b39.png)

**Comment by asgothian** [comment]
Please enter the ieee from the device into the state `zigbee.0.info.debugmessages`, activate all functions of the device and check the log for messages with the keyword “ELEVATED”.

a.

**Comment by nicomania** [comment]
![image](https://user-images.githubusercontent.com/35151132/165129799-d841901a-ea02-4cd8-af3a-1ca37bf1a4b4.png)

**Comment by asgothian** [comment]
Please add the device to the "exclude" list.

A.

**Comment by nicomania** [comment]
Like this?
![image](https://user-images.githubusercontent.com/35151132/165178660-426aa4d7-006b-4eed-8745-1d2ce9706b46.png)

And what will that do/help? Obviously the `action` is received in the `msg_from_zigbee`. But not correctly parsed into the datapoint. I have paired the device several times, that doesn't help. The `action` datapoint is also missing for all other Aqara buttons. But here it is not tragic, because the data point `click` works.

**Comment by asgothian** [comment]
No. There is an extra tab "Ausschliessen" in the adapter configuration. You can select the device type there, then restart the adapter.
The states provided by the adapter should change.

A.

**Comment by nicomania** [comment]
ok, after the restart I got additional datapoints `single `and `double`. These are updated upon press. If this is the soulution.... It is ok for me. Than you! 
Would you mind to explain, why this seems to be special? Will this be fixed in future zigbee versions?

**Comment by asgothian** [comment]
> Would you mind to explain, why this seems to be special? Will this be fixed in future zigbee versions?

Initially, the zigbee-herdsman-converters did not have as system to tell a connected client application (e.g. ioBroker) which data points are available and how they can be used. Therefore, it was necessary to provide a device definition within ioBroker which matches the data provided by the zigbee-herdsman-converters. 
Most of the older devices still have this dedicated device definition within the zigbee Adapter. From time to time, the zigbee-herdsman-converters would change the messages they send, mostly in order to harmonise the messages across different devices of a similar type. This always required updates on the ioBroker zigbee side as well.
Roughly when the zigbee-adapter reached version 1.5, the converters started to provide "exposes" in which they tell the client application which messages are accepted and how these should be interpreted / sent. The 1.5.x and newer adapter versions are capable of using this method for any device which does not have a dedicated device description. It was discussed to remove the dedicated device descriptions for all devices, but as this was considered a breaking change where a large number of states would suddenly change (appear/ disappear), we decided to generate the exclude list. Any device type which is included in this list will use the exposes for its state definition rather than the dedicated definition in the ioBroker.zigbee adapter.

in your case, the change towards the exposes also changed the messages, which is why the states which used to work no longer work. Since an active and working expose set was available we decided not to update the device definition at this point.

A.
