### ISSUE TITLE
Router identification in Map tab

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#2649]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

Hi, I just switched from Conbee II to SLZB-MR2. While a socket of mine worked well with Conbee I get this message in map generation:

<img width="624" height="102" alt="Image" src="https://github.com/user-attachments/assets/3536f5fd-59ca-43c6-8039-32a731a86548" />

Device information clearly shows "Router"

<img width="328" height="523" alt="Image" src="https://github.com/user-attachments/assets/4451f667-8848-4edd-8e9b-8dce42bc9cfc" />

### Adapter version

3.1.5

### Coordinator firmware version

Zstack 3.x.0  2-1.2.7.1

### Coordinator

SLZB-MR2

### Setup

NUC

**Comment by asgothian** [comment]
The first message is normal - the device does not support a mandatory ZCL feature for routers. The adapter detects this and informs the user about it - as the map will lack specific information on any device routed through that device.

The second message is also normal - it seems you tried to do a check for firmware updates and a device did not respond to that request. It would be interesting to see which device has the given ieee.

Other than that, I’d say the behavior is normal.

A.

**Comment by daniel-lo** [comment]
sure the Coordinator and the Ikea Button:

<img width="662" height="404" alt="Image" src="https://github.com/user-attachments/assets/e7ac7f91-50c8-46e1-b77c-14dcafedb2ef" />

**Comment by asgothian** [comment]
Definitely normal behavior for the 3.1.5 version.

The ikea remote was asleep when you did the firmware check. It does support firmware updates, but needs to be awoken before the firmware update check in order to respond.

The coordinator does not support firmware updates - this is already addressed in 3.2.x.

A.

**Comment by daniel-lo** [comment]
TBH .. I don't even have the slightest idea how to do a firmware check on the ikea button (on any device in the adapter). Naturally the Coordinator is updated via device GUI .. but else?!?

**Comment by daniel-lo** [comment]
The bottom line is .. I was the culprit ;-)

**Comment by daniel-lo** [comment]
"The first message is normal - the device does not support a mandatory ZCL feature for routers."
Which means the sockets that I just bought are useless if I wanted them to act as routers? Meaning they will probably work as routers but will drive me crazy because of the lacking information I see?

I do wonder though why Conbee didn't complain.

**Comment by daniel-lo** [comment]
After installing 3.2.2 I was able to delete the socket. I now have a setup with several of those sockets and they seem to be playing along well. Map generation errors persist .. and it seems to show by not having signal-strength values on the connecting lines.
Will have to monitor for a while now to see what's happening. I did hope the MR2 would not require as many routers as the Conbee II but that is not the case.
