### ISSUE TITLE
Please implement Philips HUE Living Colors Iris

### ISSUE THREAD

**Issue by hawi1981** [ioBroker/ioBroker.zigbee#72]
As already described in the headline, please add the Philips HUE Living Colors Iris

**Comment by arteck** [comment]
we need more information.. ..

**Comment by Kandy84** [comment]
Dear Developer of zigbee adapter,
I do have the same wish. I have a Philips HUE Living Colors Iris which is not detected by the pairing process. I could exclude a general issue with it because 2 XIAOMI zigbee devices are working well.
For starting the pairing with the Iris pressed the ON button on the remote for some seconds until the indicator led on the remote as well as the Iris starts to flash, without success. The countdown of the zigbee adapter reached zero without detecting the Iris or the remote.
Also the reset button beside the batteries (back of the remote) did not solf the problem.

Thanks for your help in advance.

**Comment by Garfonso** [comment]
Hi,

for me the pairing did work (I did it as described by @Kandy84 ) and the Iris is displayed in the network also. But in objects there is only a single object for the Iris not a channel like for the other devices. So I can not control it in any way.
It is detected as LLC010. In the documentation of the zigbee2mqtt project it says Iris would be supported. Maybe you can copy support from there? https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices

@arteck what information do you need? I can try to provide it. It would be great to control the Iris similar to the Hue Lightstrips.

**Comment by arteck** [comment]
done check my repo
https://github.com/arteck/ioBroker.zigbee

**Comment by hawi1981** [comment]
> It is detected as LLC010. In the documentation of the zigbee2mqtt project it says Iris would be supported. Maybe you can copy support from there? 

I Have the same Problem
![instances - iobroker 2018-11-02 16-36-50](https://user-images.githubusercontent.com/43812894/47925093-94b6e700-debd-11e8-8a0c-96b9d3b7e1cf.png)

**Comment by arteck** [comment]
check my repo

**Comment by Kandy84** [comment]
Hi @Garfonso,
wow that is strange that  you can pair your Iris.
Could you do me a favour and explain me step by step your way of doing it.
- Do you have a Hue Bridge activated during paring?
- What is the distance between Remote, Iris and the CC2531 during paring?
- What exactly did you do during the zigbee adapter counts from 60 to zero?
- Could I create some logs, that would help do identifiy the problem?
I know that are stupid questions....:-(
Thanks for your help.

**Comment by Kandy84** [comment]
HI @Garfonso,
thanks for your reply. Saidly pairing the Iris with the CC2531 is still not possible.
Which "PairID" and "Kanal" is set in your IOBroker Zigbee instance?
I´m currently using the default values PairID = 6754, Kanal = 11
What is printed out on your console of zigbee adapter during pairing?
I see only the Time left: 60 ... Time left: 0
Again thanks for your help

**Comment by Garfonso** [comment]
Hi @Kandy84,

that is what happens, when pairing does not work at all.... if something is working (and then usually it works ok) it says something like
`Interview state: step 1 1/2. progress: x%` 
This will count up to 100%. 
With the Iris (and also the lightstrip) this then ends with 
`Interview state: 242/2. progress 100%`
And then it prints
`New device joined 0x[someIDString] model LLC010` (in case of Iris).

I did indeed use the default settings and as I wrote above I had trouble pairing the Iris again, after I deleted it. In fact everything was a bit unstable the last days... So I did switch the ID to 6753 and switched channel to 16 and re-paired all my devices. Now it works fine (at least the light bulbs, the remote does not work at all right now...?). I paired the Iris as first device, though. 

I am not entirely sure what happened here. I think maybe the iris or the CC2531 itself somehow remembered each other, although I removed it from ioBroker and reseted it. After the ID change it worked fine (and maybe switchting channel was a good idea because there were interferences on the old one? I think my WiFi is on the same frequency). 

What I learned today: It should not be necessary to reset the device all the time. What worked for me, too, was to reset the device (i.e. use the HUE remote, keep it pressed until the device flashes, keep pressed until it glows solid again), then unplug it, then activate pairing mode in ioBroker and plug the device in.
Then pairing should work, too. That was the most reliable way to get the Iris to work, that I found today.

**Comment by Garfonso** [comment]
@arteck 
I can now confirm that Iris support works for me. Thanks. :-)

**Comment by Kandy84** [comment]
Hi again,
@Garfonso, thanks for your comprehensive reply.
I played with all possible setting (PairID and Channel) of zigbee adapter, without success.
Additionally I started the pairing of Iris with Remote, hold Remote button pressed >10sec until the Iris stops flashing and then disconnect Iris from power supply. Afterwards I started the pairing without success.
I tried also to reset the remote itself with its small reset button close to the batteries. -> no success.

Does anyone know how to log the data which the CC2531 receives?

Thanks to all of you

**Comment by arteck** [comment]
i think the old Iris works only with the remote, doesn't work with this Stick..
i have here same iris with 2 old plugs .. no chance

**Comment by handy80** [comment]
Hey guys, great work, I will try my 2 Irises (tow different versions (remote and iris) from the outer appearance) too. Maybe we can compare the versions of Irises and Remotes to be sure what devices are compatible and which are not. As soon as I can, I will add pictures here.

**Comment by Kandy84** [comment]
Hi @handy80,
my Iris (Modell: LLC006, SW: 4.6.0.8.74) and Remote HRC0303 are not working on my side. At least I didn´t had success with pairing.

**Comment by treksn** [comment]
I can't get my Iris LLC010 working with zigbee2mqtt. I really tried everything. With the zboss sniffer I can see the zigbee packages when I turn on/off the lamp after pairing the remote with the lamp. I don't have a hue bridge, I just use the Iris with the (clickwheel) remote and 2531. Any advice? Do I miss something?

My log:
```
Configuration file found: /share/zigbee2mqtt/configuration.yaml
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
2019-03-06T02:14:18: PM2 log: Launching in no daemon mode
2019-03-06T02:14:18: PM2 log: App [npm:0] starting in -fork mode-
2019-03-06T02:14:18: PM2 log: App [npm:0] online
> zigbee2mqtt@1.1.1 start /zigbee2mqtt-1.1.1
> node index.js
  zigbee2mqtt:info 3/6/2019, 2:14:22 AM Logging to directory: '/share/zigbee2mqtt/log/2019-03-06.02-14-22'
  zigbee2mqtt:debug 3/6/2019, 2:14:22 AM Removing old log directory '/share/zigbee2mqtt/log/2019-03-02.09-30-27'
  zigbee2mqtt:debug 3/6/2019, 2:14:22 AM Using zigbee-shepherd with settings: '{"net":{"panId":6754,"channelList":[11],"precfgkey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]},"dbPath":"/share/zigbee2mqtt/database.db","sp":{"baudRate":115200,"rtscts":true}}'
  zigbee2mqtt:debug 3/6/2019, 2:14:23 AM Loaded state from file /share/zigbee2mqtt/state.json
  zigbee2mqtt:info 3/6/2019, 2:14:23 AM Starting zigbee2mqtt version 1.1.1 (commit #unknown)
  zigbee2mqtt:info 3/6/2019, 2:14:23 AM Starting zigbee-shepherd
  zigbee2mqtt:info 3/6/2019, 2:14:27 AM zigbee-shepherd started
  zigbee2mqtt:info 3/6/2019, 2:14:27 AM Coordinator firmware version: '20190109'
  zigbee2mqtt:debug 3/6/2019, 2:14:27 AM zigbee-shepherd info: {"enabled":true,"net":{"state":"Coordinator","channel":11,"panId":"0x1a62","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b001936aba3","nwkAddr":0},"firmware":{"transportrev":2,"product":0,"version":"2.6.3","revision":20190109},"startTime":1551834867,"joinTimeLeft":0}
  zigbee2mqtt:info 3/6/2019, 2:14:27 AM Currently 0 devices are joined:
  zigbee2mqtt:warn 3/6/2019, 2:14:27 AM `permit_join` set to  `true` in configuration.yaml.
  zigbee2mqtt:warn 3/6/2019, 2:14:27 AM Allowing new devices to join.
  zigbee2mqtt:warn 3/6/2019, 2:14:27 AM Set `permit_join` to `false` once you joined all devices.
  zigbee2mqtt:info 3/6/2019, 2:14:27 AM Zigbee: allowing new devices to join.
  zigbee2mqtt:info 3/6/2019, 2:14:27 AM Connecting to MQTT server at mqtt://192.168.188.23:1883
  zigbee2mqtt:info 3/6/2019, 2:14:28 AM zigbee-shepherd ready
  zigbee2mqtt:info 3/6/2019, 2:14:28 AM Connected to MQTT server
  zigbee2mqtt:info 3/6/2019, 2:14:28 AM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
  zigbee2mqtt:debug 3/6/2019, 2:14:28 AM Mounted the cieApp (epId 11)](url)
```
... nothing happens ...

My conf:
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": true,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.188.23:1883",
  "serial_port": "/dev/ttyACM0",
  "devices": [],
  "network_key": [],
  "log_level": "debug",
  "include_device_information": true,
  "overwrite": true
}
```


My database.db
```
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b001936aba3","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1551832446,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[0,1281,3],"outClusterList":[1280,1282,3],"clusters":{"genBasic":{"dir":{"value":1},"acls":{"zclVersion":"R","hwVersion":"R","manufacturerName":"R","modelId":"R","dateCode":"R","powerSource":"R","locationDesc":"RW","physicalEnv":"RW","deviceEnabled":"RW"},"attrs":{"zclVersion":1,"hwVersion":1,"manufacturerName":"sivann inc.","modelId":"hiver0001","dateCode":"20170407","powerSource":1,"locationDesc":"    ","physicalEnv":0,"deviceEnabled":1}},"ssIasAce":{"dir":{"value":1}},"ssIasZone":{"dir":{"value":2},"cmdRsps":{"enrollReq":{"exec":"_exec_"},"statusChangeNotification":{"exec":"_exec_"}}},"ssIasWd":{"dir":{"value":2}},"genIdentify":{"dir":{"value":3},"acls":{"identifyTime":"RW"},"attrs":{"identifyTime":0}}}}},"_id":"VebGSvGKRcDq2Jlo"}
{"$$indexCreated":{"fieldName":"id","unique":true,"sparse":false}}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b001936aba3","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1551834867,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}}},"_id":"VebGSvGKRcDq2Jlo"}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b001936aba3","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1551834867,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[0,1281,3],"outClusterList":[1280,1282,3],"clusters":{"genBasic":{"dir":{"value":1},"acls":{"zclVersion":"R","hwVersion":"R","manufacturerName":"R","modelId":"R","dateCode":"R","powerSource":"R","locationDesc":"RW","physicalEnv":"RW","deviceEnabled":"RW"},"attrs":{"zclVersion":1,"hwVersion":1,"manufacturerName":"sivann inc.","modelId":"hiver0001","dateCode":"20170407","powerSource":1,"locationDesc":"    ","physicalEnv":0,"deviceEnabled":1}},"ssIasAce":{"dir":{"value":1}},"ssIasZone":{"dir":{"value":2},"cmdRsps":{"enrollReq":{"exec":"_exec_"},"statusChangeNotification":{"exec":"_exec_"}}},"ssIasWd":{"dir":{"value":2}},"genIdentify":{"dir":{"value":3},"acls":{"identifyTime":"RW"},"attrs":{"identifyTime":0}}}}},"_id":"VebGSvGKRcDq2Jlo"}
```

Sniffing seems to work?:
![image](https://user-images.githubusercontent.com/2706298/53849946-fbf2be00-3fb9-11e9-85b3-5b29d7bbc9ef.png)
